"""empty message

Revision ID: 70b683ca60bf
Revises: 5fceb0025bf8
Create Date: 2021-04-23 16:36:38.034501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b683ca60bf'
down_revision = '5fceb0025bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('transactions', sa.Column('expense_date', sa.Date(), nullable=False))
    op.add_column('transactions', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_groupId_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'groups', ['group_id'], ['id'])
    op.drop_column('transactions', 'groupId')
    op.drop_column('transactions', 'expenseDate')
    op.drop_column('transactions', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('createdAt', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('expenseDate', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('groupId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_groupId_fkey', 'transactions', 'groups', ['groupId'], ['id'])
    op.drop_column('transactions', 'group_id')
    op.drop_column('transactions', 'expense_date')
    op.drop_column('transactions', 'created_at')
    op.drop_table('comments')
    op.drop_table('group_membership')
    # ### end Alembic commands ###
