"""empty message

Revision ID: 1f63c6cc00d9
Revises: b61e61131b73
Create Date: 2021-04-27 09:11:24.524026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f63c6cc00d9'
down_revision = 'b61e61131b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_debt')
    op.drop_column('users', 'total_owed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_owed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_debt', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
