"""empty message

Revision ID: 1b043837492e
Revises: b61e61131b73
Create Date: 2021-04-26 16:49:01.727725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b043837492e'
down_revision = 'b61e61131b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_owed')
    op.drop_column('users', 'total_debt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_debt', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_owed', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
