"""empty message

Revision ID: 9e92d69030bf
Revises: b61e61131b73
Create Date: 2021-04-26 17:49:45.944189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e92d69030bf'
down_revision = 'b61e61131b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('transaction_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('lender_id', sa.Integer(), nullable=True),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('users', 'total_debt')
    op.drop_column('users', 'total_owed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_owed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_debt', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_table('transaction_expenses')
    op.drop_table('group_membership')
    # ### end Alembic commands ###
